config/routes.rb
Rails.application.routes.draw do
  resources :orders, :only => [:index, :create, :show]

  resource :shopping_carts, :only => [:show]
  post 'cart/del_item/', to: 'shopping_carts#delete_item', as: :delete_item
  post 'cart/add_item/', to: 'shopping_carts#add_item', as: :add_item

  resources :products, only: [:show]
  resources :categories, only: [:index, :show]

  #get 'info', to: 'static_pages#info', as: 'info'

  # Devise gem for users
  devise_for :users

  # Administrate gem
  namespace :admin do
    resources :users
    resources :categories
    resources :orders
    resources :products
    resources :purchases
    resources :shopping_carts

    root to: "users#index"
  end

  root to: 'categories#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :purchases

  def total_cost()
    summ = 0.0
    purchases.each do |purchase|
      summ += purchase.amount * purchase.product.price
    end
    return summ
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :order
  belongs_to :shopping_cart
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user
  has_many :purchases
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  has_one :shopping_cart
  has_many :orders

  def role()
    return admin
  end

  after_create :create_cart
  private
    def create_cart
      create_shopping_cart
      save
    end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Order.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Order.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/purchases_controller.rb
module Admin
  class PurchasesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Purchase.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Purchase.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.all
  end

  def show
    order_id = params[:id]

    @order = current_user.orders.find(order_id)
  end

  def create
    purchases = current_user.shopping_cart.purchases
    if purchases.empty?
      flash[:alert] = "Cart is empty"
    else
      @order = Order.new
      @order.purchases = purchases
      @order.user = current_user
      @order.save
      current_user.shopping_cart.purchases.clear
    end
    redirect_to :shopping_carts
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!

  # cart
  def show
    @cart = current_user.shopping_cart
  end

  # add_item/:id
  def add_item
    @product = Product.find(params[:id])
    amount = Integer(params[:amount])
    if amount <= @product.amount && amount > 0
      purchase = Purchase.new(amount: amount)
      @product.amount -= amount

      purchase.product = @product
      purchase.save
      @product.save

      current_user.shopping_cart.purchases << purchase
      current_user.shopping_cart.save

      notice = {:buy_success => "Successfully added #{amount} #{@product.name} to Cart"}
    else
      notice = {:buy_danger => "Invalid amount of purchase"}
    end

    if request.referrer.nil?
      redirect_to @product, :flash => notice
    else
      redirect_to request.referrer, :flash => notice # todo may be use here head request
    end
  end

  #delete_item/:id
  def delete_item
    purchase = Purchase.find(params[:id])
    purchase.product.amount += purchase.amount
    purchase.product.save
    current_user.shopping_cart.purchases.delete(purchase)
    redirect_to controller: :shopping_carts, action: :show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/index.html.erb
<%= stylesheet_link_tag "categories"%>

<h1>Product categories</h1>
<% @categories.each do |category| %>
<div class="row">
    <div class="categories-info panel panel-default col-md-3">
        <div class="panel-heading"><%= link_to category.name, category%></div>
        <div class="panel-body">
            <%= image_tag(category.image_url, :class => 'img-rounded category_img') %>
            <div class="description well"><%= category.description %></div>
        </div>
    </div>
</div>
<% end %>

<%# link_to 'New Product', new_product_path %>

app/views/categories/show.html.erb
<%= stylesheet_link_tag "categories", media: "all", "data-turbolinks-track" => "reload" %>

<h2>Category <%= @category.name %></h2>
<h3>Description: <%= @category.description %> </h3>

<% if flash[:buy_success] %>
    <div class="alert alert-success"><%= flash[:buy_success] %></div>
<% elsif flash[:buy_danger] %>
    <div class="alert alert-danger"><%= flash[:buy_danger] %></div>
<% end %>

<% @products.each do |product| %>
    <div class = "row">
      <div class="category-info col-md-12 center-block well">
        <h3><%= link_to product.name, product %></h3>
        <%= image_tag(product.image_url) %>
        <div><%= product.description %></div><hr>
        <div>Lasts: <%= product.amount %></div>
        <div>Price: <%= product.price %></div>
        <div>Id: <%= product.id %></div>
        <% if product.amount > 0 %>
            <%= form_tag({:controller => :shopping_carts, :action => :add_item, :id => product.id}, :method => :post) do %>
                <%= number_field_tag(:amount, 1) %>
                <%= submit_tag("Add to cart") %>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/orders/index.html.erb
<%= stylesheet_link_tag 'orders' %>

<h1>Orders</h1>
<% if @orders.empty? %>
    <div class="alert alert-warning">
      <strong> You have no orders</strong>
    </div>

<% else %>
    <table class="table">
      <tr>
        <td>Order</td>
        <td>Date</td>
        <td>Purchases</td>
        <td>Total cost</td>
      </tr>

    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", "orders/#{order.id}" %></td>
        <td><ul>
          <% order.purchases.each do |purchase| %>
              <li><%= link_to purchase.product.name, purchase.product %> (<%= purchase.amount %>)</li>
          <% end %>
        </ul></td>
        <td>
          <%= order.created_at %>
        </td>
        <td><%= order.total_cost %></td>
      </tr>
    <% end %>
    </table>
<% end %>

app/views/orders/show.html.erb
<h1>Order <%= @order.id %></h1>

<div class="well">
<p>Date: <%= @order.created_at %></p>
Purchases
<ul>
  <% @order.purchases.each do |purchase| %>
      <li><%= link_to purchase.product.name, purchase.product %> (<%= purchase.amount %>)</li>
  <% end %>
</ul>
<div>Total cost: <%= @order.total_cost %></div>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h2><%= @product.description %></h2>

<div></div>
<%= image_tag(@product.image_url) %>
<div>
  Amount: <%= @product.amount %>
</div>

<div>
  Price: <%= @product.price %>
</div>

<% if @product.amount > 0 %>
    <%= form_tag({:controller => :shopping_carts, :action => :add_item, :id => product.id}, :method => :post) do %>
        <%= hidden_field_tag(:id, @product.id)%>
        <%= submit_tag("Add to cart") %>
    <% end %>
<% end %>

<% if flash[:buy_success] %>
    <div class="alert alert-success"><%= flash[:buy_success] %></div>
<% elsif flash[:buy_danger] %>
    <div class="alert alert-danger"><%= flash[:buy_danger] %></div>
<% end %>